"""add table articles tags

Revision ID: 05e65bf85f23
Revises: df70fd431dc9
Create Date: 2019-12-13 14:56:32.633800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e65bf85f23'
down_revision = 'df70fd431dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
