"""add three time filed

Revision ID: 0a43e5b16392
Revises: 09bb3bdff13d
Create Date: 2019-12-12 09:37:35.933531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a43e5b16392'
down_revision = '09bb3bdff13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('verficode', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('verficode', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('verficode', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verficode', 'updated_at')
    op.drop_column('verficode', 'deleted_at')
    op.drop_column('verficode', 'created_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'created_at')
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'deleted_at')
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###
