"""add three time filed

Revision ID: 9299cbcf6d8b
Revises: ed535bd21f09
Create Date: 2019-12-12 15:35:20.075155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9299cbcf6d8b'
down_revision = 'ed535bd21f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questions_id', table_name='questions')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_verficode_id', table_name='verficode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_verficode_id', 'verficode', ['id'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    # ### end Alembic commands ###
