"""add three time filed

Revision ID: ed535bd21f09
Revises: 0a43e5b16392
Create Date: 2019-12-12 13:44:51.913300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed535bd21f09'
down_revision = '0a43e5b16392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
